# Generated by Django 5.1.7 on 2025-08-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(help_text='WhatsApp number with country code, e.g., 254700123456', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('map_embed_url', models.TextField(help_text='Google Maps embed iframe URL')),
                ('operating_hours', models.TextField(help_text='e.g., Mon-Fri: 8am - 6pm')),
                ('emergency_contact', models.CharField(max_length=100)),
            ],
        ),
    ]
